services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statements
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    command: uvicorn bank_statements_api.main:app --host 0.0.0.0 --port 10000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/statements
    ports:
      - "10000:10000"
    volumes:
      - .:/app
volumes:
  postgres_data:
